[package]
name = "advent_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
pico-args = { version = "0.5.0", features = ["short-space-opt", "combined-flags"] }
regex = "1.11.1"
itertools = "0.13.0"
hashbrown = "0.15.2"
prettytable-rs = "0.10.0"